[package]
name = "superwire-dsl"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
petgraph = { workspace = true }
superwire-semantic = { path = "../superwire-semantic" }
superwire-types = { path = "../superwire-types" }
thiserror = { workspace = true }
