id = "superwire"
name = "Superwire"
description = "Superwire language support for Zed."
version = "0.1.0"
schema_version = 1
authors = ["Superwire <support@superwire.dev>"]
repository = "https://github.com/milewski/superwire"

[grammars.superwire]
repository = "https://github.com/milewski/superwire"
rev = "7dd0fba9f7908d7578019d8eb4019ca9dadf9153"
path = "editors/zed/tree-sitter-superwire"

[language_servers.superwire-lsp]
name = "Superwire LSP"
languages = ["Superwire"]

[[capabilities]]
kind = "process:exec"
command = "*"
args = ["**"]
