/**
 * Tool schema example:
 * - `tool input` fields are generated by the model when it calls the tool.
 * - `tool bounded` fields are fixed by the workflow author (from `input`, `secrets`, or agent outputs).
 *
 * Friendly scenario:
 * generate a short announcement and create a deterministic fingerprint for it.
 *
 * The model generates announcement text (`headline`, `summary`).
 * The tool receives bounded values (`collection_id` from input and `signing_salt` from secrets)
 * and returns only new data: a SHA-256 fingerprint and a short code.
 */
import { Engine, Workflow } from '../src'
import { loadOpenAIProviderSecrets, type OpenAIProviderSecrets } from './env'
import { ContentFingerprint, type ContentFingerprintOutput } from './tools'

type Input = {
    collection_id: string;
    topic: string;
    audience: string;
}

type WorkflowOutput = {
    announcement: {
        headline: string;
        summary: string;
    };
    content_fingerprint: ContentFingerprintOutput;
}

type Secrets = OpenAIProviderSecrets & {
    fingerprint_salt: string;
}

async function runToolSchemaExample(): Promise<void> {
    const engine = new Engine()

    try {
        const inputs: Input = {
            collection_id: 'spring-launch-2026',
            topic: 'community cleanup day',
            audience: 'local neighborhood members',
        }

        const secrets: Secrets = {
            ...loadOpenAIProviderSecrets(),
            fingerprint_salt: 'demo-fingerprint-salt-change-me',
        }

        const workflow = Workflow.fromFile<WorkflowOutput, Input, Secrets>(
            './examples/workflows/tool_schema.wire',
            inputs,
            secrets,
            [ new ContentFingerprint() ],
        )

        const response = await engine.run(workflow)

        if (await response.isError()) {
            console.error('Error:', await response.error())

            return
        }

        console.log(await response.success())
    } finally {
        engine.close()
    }
}

runToolSchemaExample()
