[package]
name = "engine_ai_cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
engine-ai-core = { path = "../core" }
clap = { version = "4.5", features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
colog = { workspace = true }

[lints]
workspace = true
