[package]
name = "superwire-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "superwire-cli"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
clap = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
superwire-agent = { path = "../agent" }
superwire-core = { path = "../core" }
thiserror = { workspace = true }
tokio = { workspace = true }
jsonschema = { workspace = true }
