use clap::{Arg, ArgAction, Command};
use engine_ai_core::runtime::types::WorkflowType;
use std::collections::BTreeMap;

use crate::diagnostics::CommandError;
use crate::execution::{compile_dynamic_workflow_from_source, execute_compiled_workflow};

const SECRET_ARGUMENT_NAME: &str = "secret";

pub fn run_generated_workflow(workflow_source: &str) -> Result<(), CommandError> {
    let dynamic_compiled_workflow = compile_dynamic_workflow_from_source(workflow_source)?;
    let input_fields = extract_input_fields(dynamic_compiled_workflow.input_type());
    let launcher_command = GeneratedLauncherCommand::new(input_fields);

    let Some(invocation_arguments) = launcher_command.parse_invocation_arguments_from_environment()? else {
        return Ok(());
    };

    let workflow_output = execute_compiled_workflow(dynamic_compiled_workflow, &invocation_arguments)?;
    let rendered_output = serde_json::to_string_pretty(&workflow_output)
        .map_err(|error| CommandError::internal(format!("failed to serialize workflow output: {error}")))?;

    println!("{rendered_output}");

    Ok(())
}

#[derive(Debug, Clone)]
struct GeneratedLauncherCommand {
    input_fields: BTreeMap<String, WorkflowType>,
}

impl GeneratedLauncherCommand {
    fn new(input_fields: BTreeMap<String, WorkflowType>) -> Self {
        Self { input_fields }
    }

    fn parse_invocation_arguments_from_environment(&self) -> Result<Option<Vec<String>>, CommandError> {
        let clap_command = self.build_clap_command();

        match clap_command.try_get_matches_from(std::env::args_os()) {
            Ok(argument_matches) => Ok(Some(self.render_invocation_arguments(&argument_matches))),
            Err(clap_error) => match clap_error.kind() {
                clap::error::ErrorKind::DisplayHelp | clap::error::ErrorKind::DisplayVersion => {
                    clap_error
                        .print()
                        .map_err(|error| CommandError::internal(format!("failed to render launcher help output: {error}")))?;

                    Ok(None)
                }
                _ => Err(CommandError::invalid_workflow(clap_error.to_string())),
            },
        }
    }

    fn build_clap_command(&self) -> Command {
        let mut command = Command::new("engine-ai-workflow")
            .about("Standalone executable generated by engine-ai build")
            .arg(
                Arg::new(SECRET_ARGUMENT_NAME)
                    .long(SECRET_ARGUMENT_NAME)
                    .value_name("NAME=VALUE")
                    .num_args(1)
                    .action(ArgAction::Append)
                    .allow_hyphen_values(true)
                    .help("Provide a workflow secret assignment"),
            );

        for (field_name, field_type) in &self.input_fields {
            let leaked_field_name = leak_static_string(field_name);

            command = command.arg(
                Arg::new(leaked_field_name)
                    .long(leaked_field_name)
                    .value_name("VALUE")
                    .num_args(0..=1)
                    .allow_hyphen_values(true)
                    .help(format!("Workflow input field of type `{field_type}`")),
            );
        }

        command
    }

    fn render_invocation_arguments(&self, argument_matches: &clap::ArgMatches) -> Vec<String> {
        let mut invocation_arguments = Vec::new();

        for field_name in self.input_fields.keys() {
            if !argument_matches.contains_id(field_name) {
                continue;
            }

            invocation_arguments.push(format!("--{field_name}"));

            if let Some(raw_field_value) = argument_matches.get_one::<String>(field_name) {
                invocation_arguments.push(raw_field_value.clone());
            }
        }

        if let Some(secret_assignments) = argument_matches.get_many::<String>(SECRET_ARGUMENT_NAME) {
            for secret_assignment in secret_assignments {
                invocation_arguments.push("--secret".to_string());
                invocation_arguments.push(secret_assignment.clone());
            }
        }

        invocation_arguments
    }
}

fn extract_input_fields(input_type: Option<&WorkflowType>) -> BTreeMap<String, WorkflowType> {
    let Some(input_type) = input_type else {
        return BTreeMap::new();
    };

    let WorkflowType::Object(input_fields) = input_type else {
        return BTreeMap::new();
    };

    input_fields.clone()
}

fn leak_static_string(value: &str) -> &'static str {
    Box::leak(value.to_owned().into_boxed_str())
}
