[package]
name = "engine-ai-example"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
engine-ai-core = { path = "../core" }
ollama-rs = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
colog = { workspace = true }
serde_json = { workspace = true }
