[package]
name = "superwire-core"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
schemars = { workspace = true }
serde_json = { workspace = true }
superwire-dsl = { path = "../superwire-dsl" }
superwire-mcp = { path = "../superwire-mcp" }
superwire-semantic = { path = "../superwire-semantic" }
