[package]
name = "engine-ai-core"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
pest = { workspace = true }
pest_derive = { workspace = true }
petgraph = { workspace = true }
rayon = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
log = { workspace = true }
ollama-rs = { workspace = true }
jsonschema = { workspace = true }
async-trait = "0.1"
regex = { workspace = true }
reqwest = { workspace = true }
