[package]
name = "superwire-core"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
ariadne = "0.6.0"
async-trait = "0.1"
superwire-agent = { path = "../agent" }
futures = "0.3"
jsonschema = { workspace = true }
pest = { workspace = true }
pest_derive = { workspace = true }
petgraph = { workspace = true }
reqwest = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strsim = "0.11"
thiserror = { workspace = true }
tokio = { workspace = true }
