package superwire:tool@0.1.0;

interface types {
  record tool-error {
    message: string,
  }

  record tool-definition {
    name: string,
    description: string,
    parameters-schema-json: string,
    bound-parameters-schema-json: string,
    output-schema-json: string,
  }
}

interface tool {
  use types.{tool-error, tool-definition};

  execute: func(input-json: string, bound-input-json: string) -> result<string, tool-error>;
  definition: func() -> result<tool-definition, tool-error>;
}

world superwire-tool {
  export tool;
}