[package]
name = "superwire-protocol"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
base64 = "0.22"
serde = { workspace = true }
serde_json = { workspace = true }
superwire-semantic = { path = "../superwire-semantic" }
superwire-types = { path = "../superwire-types" }
