[package]
name = "superwire-executor"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
async-trait = "0.1"
axum = { version = "0.8", features = ["ws"] }
base64 = "0.22"
cersei-provider = { workspace = true }
cersei-types = { workspace = true }
clap = { workspace = true }
colog = { workspace = true }
futures = "0.3"
humantime = { workspace = true }
jsonschema = { workspace = true }
log = { workspace = true }
redis = "1.2.1"
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
superwire-core = { path = "../superwire-core" }
superwire-dsl = { path = "../superwire-dsl" }
superwire-lsp = { path = "../superwire-lsp" }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = "0.1"
tower = { version = "0.5", features = ["util"] }
tower-http = { version = "0.6", features = ["fs"] }

[dev-dependencies]
schemars = { workspace = true }
superwire-test-support = { path = "../superwire-test-support" }

[[bench]]
name = "runtime"
harness = false
