WHITESPACE = _{ " " | "\t" | NEWLINE }
COMMENT = _{ "//" ~ (!NEWLINE ~ ANY)* }

identifier = @{ (ASCII_ALPHA | "_") ~ (ASCII_ALPHANUMERIC | "_" )* }
number = @{ "-"? ~ ASCII_DIGIT+ ~ ("." ~ ASCII_DIGIT+)? }
boolean = { "true" | "false" }
null = { "null" }
string = ${ "\"" ~ string_inner* ~ "\"" }
string_inner = _{ "\\\"" | "\\\\" | (!"\"" ~ ANY) }
multiline_string = ${ "\"\"\"" ~ multiline_inner* ~ "\"\"\"" }
multiline_inner = _{ !("\"\"\"") ~ ANY }

workflow = { SOI ~ statement* ~ EOI }
statement = _{ provider_def | schema_def | input_def | output_def | agent_def }

agent_def = { terminal_marker? ~ "agent" ~ identifier ~ block }
terminal_marker = { "<-" }
provider_def = { "provider" ~ identifier ~ block }
schema_def = { "schema" ~ identifier ~ schema_block }
input_def = { "input" ~ schema_block }
output_def = { "output" ~ output_block }

block = { "{" ~ property* ~ "}" }
schema_block = { "{" ~ schema_field* ~ "}" }
output_block = { "{" ~ output_field* ~ "}" }
property = { identifier ~ left_arrow ~ property_value }
left_arrow = _{ "<-" }
property_value = _{ for_each_expr | value }

schema_field = { identifier ~ ":" ~ schema_type ~ string? }
output_field = { identifier ~ left_arrow ~ value }
schema_type = { schema_array | schema_union }
schema_array = { "[" ~ schema_type ~ "]" }
schema_union = { schema_primary ~ ("|" ~ schema_primary)* }
schema_primary = { "string" | "number" | "boolean" | "null" | string | schema_reference }
schema_reference = { "schema" ~ "." ~ identifier }
inline_schema = { "schema" ~ schema_block }

array = { "[" ~ (value ~ ("," ~ value)*)? ~ "]" }
object = { "{" ~ (object_property ~ ("," ~ object_property)*)? ~ "}" }
object_property = { identifier ~ left_arrow ~ value }

function_call = { identifier ~ value ~ object }
compact_function = { "compact" ~ object }
reference = @{ identifier ~ ("." ~ identifier)+ }
for_each_expr = { value ~ "as" ~ identifier }
value = _{ compact_function | function_call | inline_schema | array | object | multiline_string | string | number | boolean | null | reference | identifier }
